### PR TITLE
Updates to WDL makefile and README

### PR DESCRIPTION
**Pull request by prkrtg**
Update the README to include the process of having a virtual environment and then installing the requirements

Requirements file updated with proper versions for the libraries needed for wdl

Makefile cleaned up to help with testing and debugging. 
To use debug mode:
`make DEBUG=1 Demo `
By default debug mode is off and all you will need to do is `make Demo` as usual.

Example output of debug:
```
%  make DEBUG=1 Demo
Debug:  Current filename: Demo
Looking for MODULE_FILE = Demo.mod ...
Debug:  Found configuration file: Demo.conf
Making Demo_TMP.wdl from Demo.conf ...
Debug:  Created WDL file: Demo_TMP.wdl
Making Demo_TMP.script and Demo_TMP.states from Demo_TMP.wdl ...
Debug:  Found MODULE_FILE: Demo.mod
Debug:  Processed MODULE_FILE: Demo.mod
Using MOD file: /Users/lotus/Projects/wdl/demo/Demo.mod
Loading signal mnemonics from /Users/lotus/Projects/wdl/demo/Demo.signals
Wrote script to Demo_TMP.script
Wrote states to Demo_TMP.states
Catalog of timing objects:
index  label                                type  exit  time [us]
-----------------------------------------------------------------
   0:  Main                             sequence   005 106563018.13
   1:  TestMode                         sequence   005   45800.09
   2:  TestRG                           sequence   009 10000206.25
   3:  TestSW                           sequence   009 30000618.77
   4:  GrabFrame                        sequence   014 106562560.10
   5:  GrabLine                         sequence   014   95732.14
   6:  GrabPixel                        sequence   014      44.06
   7:  MilliSec                         sequence   000    1000.02
   8:  Sec                              sequence   000 1000020.02
   9:  RawPixel                         waveform   000      10.00
  10:  wDelay1us                        waveform   000       1.00
  11:  wDelay1ms                        waveform   000    1000.00
  12:  wSampleDelay                     waveform   000      10.00
  13:  SerialShiftPixelA                waveform   007      35.00
  14:  SerialShiftPixelB                waveform   014      43.00
  15:  OnlyRG_Hi                        waveform   008       3.00
  16:  OnlyRG_Lo                        waveform   009       3.00
  17:  OnlySW_Hi                        waveform   015       3.00
  18:  OnlySW_Lo                        waveform   014       3.00
  19:  ParallelShiftMPP                 waveform   021    2400.00
  20:  ClampAC                          waveform   005      13.00
  21:  TestPhase                        waveform   005     458.00
  22:  RGHi                             waveform   008       3.00
  23:  wFrame                           waveform   023       0.01
  24:  wLine                            waveform   024       0.01
  25:  wPixel                           waveform   026       0.02
Debug:  Finished waveform generation for Demo_TMP with plot: False 
Assembling Demo.acf ...
Debug:  Looking for CDS_FILE = Demo.cds ...
Debug:  Preparing to assemble Demo.acf file using:
Debug:  INCPARSER: ../incParserDriver.py
Debug:  CDSFILE: Demo.cds
Debug:  GPP Flags: +c /* */ +c // 
 +c \n 
Assembling Demo.acf file ...
Modes appended to Demo.acf
Not a git archive, skipping REV keyword
Done
```

### CODE REVIEW

**Comment by astronomerdave** [comment]
Once the venv is set up, what are the steps for building ACF files? Will it "just work" after that?

**Comment by prkrtg** [comment]
> Once the venv is set up, what are the steps for building ACF files? Will it "just work" after that?

You'll still need to run
$ make ${TARGET}

In the README
After the requirements are met, the setup section in the README states to ensure the Makefile is in the directory of your ACF source files. Lemme know though if you think it should be a bit more clear

**Comment by prkrtg** [comment]
> > You'll still need to run
> > $ make ${TARGET}
> 
> I meant will `make <target>` just work or does one need to do anything with venv again, once it's installed? @mikelangmayr 's instructions to me today were:
> 
> ```
> python3 -m venv .venv
> source .venv/bin/activate
> pip install -r requirements.txt
> then compile the .acf file
> (once you're done)
> deactivate
> ```
> 
> so since "compile" was in the middle of that I want to know if compile is always in the middle of that.

That's correct, in terms of the virtual environment, compile is always the middle of it once activated & requirements are installed.

**Review by mikelangmayr — APPROVED** [review]
Looks good

**Review by scizen9 — APPROVED** [review]
good update!

**Pull request merged**
